### ISSUE TITLE
Incompatible with new versions of interface-datastore

### ISSUE THREAD

**Issue by HexaField** [ipfs/js-datastore-idb#36]
In https://github.com/ipfs/interface-datastore `Key.toBuffer()` is now `Key.uint8Array()`

I have tried making the change, but some tests are failing.

**Comment by hugomrdias** [comment]
This datastore doesn't pass all the datastore interface tests yet, so not ready to be used.
I will get back to this asap.

**Comment by achingbrain** [comment]
`datastore-idb@2.0.0` has been updated to `interface-datastore@8.x.x`
